version: '2'
services:
    jhipsterdocumentapplication-app:
        image: jhipsterdocumentapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://jhipsterdocumentapplication-mariadb:3306/jhipsterdocumentapplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://jhipsterdocumentapplication-elasticsearch:9200
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
        ports:
            - 8080:8080
    jhipsterdocumentapplication-mariadb:
        extends:
            file: mariadb.yml
            service: jhipsterdocumentapplication-mariadb
    jhipsterdocumentapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipsterdocumentapplication-elasticsearch
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
